name: UnityTest

on:
  push:
    branches:
      - main

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testAllModes:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion: 
          - 2018.4.19f1
        testMode:
          - playmode
          - editmode

    container: docker://gableroux/unity3d:${{ matrix.unityVersion }}

    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}

    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true

      - run: mkdir -p path/to/artifact
      - run: /opt/Unity/Editor/Unity -manualLicenseFile ${{ env.UNITY_LICENSE }} -batchmode -nographics -quit || exit 0
      - run: /opt/Unity/Editor/Unity -batchmode -nographics -silent-crashes -logFile -projectPath . -runEditorTests -editorTestsResultFile path/to/artifact/results.xml || exit 0
      
      - uses: actions/upload-artifact@v2
        with:
          name: Test results for ${{ matrix.testMode }}
          path: path/to/artifact